dist: xenial
language: generic
addons:
  apt:
    packages:
    - sshpass
after_success:
- export SSHPASS=$firstPwd
- sshpass -e ssh -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -v -p $port
  $firstUser@$remote "rm -rf $path && mkdir -vp /home/$firstUser/web/ThinkSync"
- sshpass -e scp -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -v -P $port
  -r $TRAVIS_BUILD_DIR/* $firstUser@$remote:/home/$firstUser/web/ThinkSync/.
- export SSHPASS=$secondPwd
- sshpass -e ssh -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -v -p $port
  $secondUser@$remote "rm -rf $path && mkdir -vp /home/$secondUser/web/ThinkSync"
- sshpass -e scp -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -v -P $port
  -r $TRAVIS_BUILD_DIR/* $secondUser@$remote:/home/$secondUser/web/ThinkSync/.
env:
  global:
    secure: nHiXlW7V+Wmw0EJJ/0Ybrf6IEy8Qz9sVlwCvww32tXIjtFuIFUA+dy7uR0GnOIpmzbGwZNMfpWQBz3Q/PuOJNz7tDJUr2dpnXgQWz0PLp4Uu+jqDNJH5JOpCLU4mgWtProdLOhDyNTF3MZSylG0qhk53B0kW4B5y9QsQxPTWHZHUdSuSxDTI5vkLVCE1j4d3S6JLMQQZGlxnoEOZMj5cqES281MhjzdZt3XPYk/adHIx20EtmjY3C3Okvb/T8iWvOUuFxdwRYJlHXancv3z50CR3mlFDlMYcSuZRs4lP8yyhRlcEHsNwwGmXsFzU8mfApUrKMmOReSxRtkVc3TptO/NyfVRCBg8IJHDvPa4U5ciYxkDtk4eCvPWAmPvQEipVd6Yi9dsV1TntQm7IbOLX0RfLZOUfRgO1c44e5QbZLx8k2WG5d4/8Rgi8ctvX610HUcc7NjHg6tp0XuibjkGul4/MPe9p9CZSiAeXFYPur1xTUV5MiiFOeygLxM30ZAdqiyE2hLbFn8WbrO4wIz9FgGldJ5FQK8a+ux3mqZ4vXrb6TZAYGtGLnArmRNMQeuaTzNk0stAcIqqv4/tWea2V6iHveGoDJSSLdj7S0LaK+zwLs3yrzO5RcHSn/CoWmD97p5q84Go/DQ/7WGUG9U/HIKc879c/DOqxXKufNEdpS7M=
