version: '2'

services:
  web:
    build:
      dockerfile: nginxDocker
      context: .
    ports:
      - 8080:80
    links:
      - db

  db:
    image: mariadb:10.3.16
    restart: always
    volumes:
      - ../ThinkSync-Coding.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 8081:3306
    
